// export interface DistanceFromNodeList {
//     [key:string]: number;// ex: "H06: 0.8"
//     isConfirmed: string;// true-> 確定距離, false -> 暫定距離
// }
export interface DistanceFromNodeList {
  [key: string]: Array<{
    distance: number;// 始点からの距離(デフォルトは999)
    isConfirmed: boolean;// true: 確定距離, false: 暫定距離
  }>;
}

export const distanceFromNodeList: DistanceFromNodeList ={
  // 東山線
    H01: [{distance: 999, isConfirmed: false}],
    H02: [{distance: 999, isConfirmed: false}],
    H03: [{distance: 999, isConfirmed: false}],
    H04: [{distance: 999, isConfirmed: false}],
    H05: [{distance: 999, isConfirmed: false}],
    H06: [{distance: 999, isConfirmed: false}],
    H07: [{distance: 999, isConfirmed: false}],
    H08: [{distance: 999, isConfirmed: false}],
    H09: [{distance: 999, isConfirmed: false}],
    H10: [{distance: 999, isConfirmed: false}],
    H11: [{distance: 999, isConfirmed: false}],
    H12: [{distance: 999, isConfirmed: false}],
    H13: [{distance: 999, isConfirmed: false}],
    H14: [{distance: 999, isConfirmed: false}],
    H15: [{distance: 999, isConfirmed: false}],
    H16: [{distance: 999, isConfirmed: false}],
    H17: [{distance: 999, isConfirmed: false}],
    H18: [{distance: 999, isConfirmed: false}],
    H19: [{distance: 999, isConfirmed: false}],
    H20: [{distance: 999, isConfirmed: false}],
    H21: [{distance: 999, isConfirmed: false}],
    H22: [{distance: 999, isConfirmed: false}],
    // 名城線
    M01: [{distance: 999, isConfirmed: false}],
    M02: [{distance: 999, isConfirmed: false}],
    M03: [{distance: 999, isConfirmed: false}],
    M04: [{distance: 999, isConfirmed: false}],
    M05: [{distance: 999, isConfirmed: false}],
    M06: [{distance: 999, isConfirmed: false}],
    M07: [{distance: 999, isConfirmed: false}],
    M08: [{distance: 999, isConfirmed: false}],
    M09: [{distance: 999, isConfirmed: false}],
    M10: [{distance: 999, isConfirmed: false}],
    M11: [{distance: 999, isConfirmed: false}],
    M12: [{distance: 999, isConfirmed: false}],
    M13: [{distance: 999, isConfirmed: false}],
    M14: [{distance: 999, isConfirmed: false}],
    M15: [{distance: 999, isConfirmed: false}],
    M16: [{distance: 999, isConfirmed: false}],
    M17: [{distance: 999, isConfirmed: false}],
    M18: [{distance: 999, isConfirmed: false}],
    M19: [{distance: 999, isConfirmed: false}],
    M20: [{distance: 999, isConfirmed: false}],
    M21: [{distance: 999, isConfirmed: false}],
    M22: [{distance: 999, isConfirmed: false}],
    M23: [{distance: 999, isConfirmed: false}],
    M24: [{distance: 999, isConfirmed: false}],
    M25: [{distance: 999, isConfirmed: false}],
    M26: [{distance: 999, isConfirmed: false}],
    M27: [{distance: 999, isConfirmed: false}],
    M28: [{distance: 999, isConfirmed: false}],
    // 名港線
    E01: [{distance: 999, isConfirmed: false}],
    E02: [{distance: 999, isConfirmed: false}],
    E03: [{distance: 999, isConfirmed: false}],
    E04: [{distance: 999, isConfirmed: false}],
    E05: [{distance: 999, isConfirmed: false}],
    E06: [{distance: 999, isConfirmed: false}],
    E07: [{distance: 999, isConfirmed: false}],
    // 鶴舞線
    T01: [{distance: 999, isConfirmed: false}],
    T02: [{distance: 999, isConfirmed: false}],
    T03: [{distance: 999, isConfirmed: false}],
    T04: [{distance: 999, isConfirmed: false}],
    T05: [{distance: 999, isConfirmed: false}],
    T06: [{distance: 999, isConfirmed: false}],
    T07: [{distance: 999, isConfirmed: false}],
    T08: [{distance: 999, isConfirmed: false}],
    T09: [{distance: 999, isConfirmed: false}],
    T10: [{distance: 999, isConfirmed: false}],
    T11: [{distance: 999, isConfirmed: false}],
    T12: [{distance: 999, isConfirmed: false}],
    T13: [{distance: 999, isConfirmed: false}],
    T14: [{distance: 999, isConfirmed: false}],
    T15: [{distance: 999, isConfirmed: false}],
    T16: [{distance: 999, isConfirmed: false}],
    T17: [{distance: 999, isConfirmed: false}],
    T18: [{distance: 999, isConfirmed: false}],
    T19: [{distance: 999, isConfirmed: false}],
    T20: [{distance: 999, isConfirmed: false}],
    // 桜通線
    S01: [{distance: 999, isConfirmed: false}],
    S02: [{distance: 999, isConfirmed: false}],
    S03: [{distance: 999, isConfirmed: false}],
    S04: [{distance: 999, isConfirmed: false}],
    S05: [{distance: 999, isConfirmed: false}],
    S06: [{distance: 999, isConfirmed: false}],
    S07: [{distance: 999, isConfirmed: false}],
    S08: [{distance: 999, isConfirmed: false}],
    S09: [{distance: 999, isConfirmed: false}],
    S10: [{distance: 999, isConfirmed: false}],
    S11: [{distance: 999, isConfirmed: false}],
    S12: [{distance: 999, isConfirmed: false}],
    S13: [{distance: 999, isConfirmed: false}],
    S14: [{distance: 999, isConfirmed: false}],
    S15: [{distance: 999, isConfirmed: false}],
    S16: [{distance: 999, isConfirmed: false}],
    S17: [{distance: 999, isConfirmed: false}],
    S18: [{distance: 999, isConfirmed: false}],
    S19: [{distance: 999, isConfirmed: false}],
    S20: [{distance: 999, isConfirmed: false}],
    S21: [{distance: 999, isConfirmed: false}],
    // 上飯田線
    K01: [{distance: 999, isConfirmed: false}],
    K02: [{distance: 999, isConfirmed: false}],
};
export default distanceFromNodeList;