export type DistanceFromNode = {
  id: string;
  distance: number; // 始点からの距離(デフォルトは999)
  isConfirmed: boolean; // true: 確定距離, false: 暫定距離
};

export type DistanceFromNodeList = DistanceFromNode[];

export const distanceFromNodeList: DistanceFromNodeList = [
  // 東山線
  { id: "H01", distance: 999, isConfirmed: false },
  { id: "H02", distance: 999, isConfirmed: false },
  { id: "H03", distance: 999, isConfirmed: false },
  { id: "H04", distance: 999, isConfirmed: false },
  { id: "H05", distance: 999, isConfirmed: false },
  { id: "H06", distance: 999, isConfirmed: false },
  { id: "H07", distance: 999, isConfirmed: false },
  { id: "H08", distance: 999, isConfirmed: false },
  { id: "H09", distance: 999, isConfirmed: false },
  { id: "H10", distance: 999, isConfirmed: false },
  { id: "H11", distance: 999, isConfirmed: false },
  { id: "H12", distance: 999, isConfirmed: false },
  { id: "H13", distance: 999, isConfirmed: false },
  { id: "H14", distance: 999, isConfirmed: false },
  { id: "H15", distance: 999, isConfirmed: false },
  { id: "H16", distance: 999, isConfirmed: false },
  { id: "H17", distance: 999, isConfirmed: false },
  { id: "H18", distance: 999, isConfirmed: false },
  { id: "H19", distance: 999, isConfirmed: false },
  { id: "H20", distance: 999, isConfirmed: false },
  { id: "H21", distance: 999, isConfirmed: false },
  { id: "H22", distance: 999, isConfirmed: false },

  // 名城線
  { id: "M01", distance: 999, isConfirmed: false },
  { id: "M02", distance: 999, isConfirmed: false },
  { id: "M03", distance: 999, isConfirmed: false },
  { id: "M04", distance: 999, isConfirmed: false },
  { id: "M05", distance: 999, isConfirmed: false },
  { id: "M06", distance: 999, isConfirmed: false },
  { id: "M07", distance: 999, isConfirmed: false },
  { id: "M08", distance: 999, isConfirmed: false },
  { id: "M09", distance: 999, isConfirmed: false },
  { id: "M10", distance: 999, isConfirmed: false },
  { id: "M11", distance: 999, isConfirmed: false },
  { id: "M12", distance: 999, isConfirmed: false },
  { id: "M13", distance: 999, isConfirmed: false },
  { id: "M14", distance: 999, isConfirmed: false },
  { id: "M15", distance: 999, isConfirmed: false },
  { id: "M16", distance: 999, isConfirmed: false },
  { id: "M17", distance: 999, isConfirmed: false },
  { id: "M18", distance: 999, isConfirmed: false },
  { id: "M19", distance: 999, isConfirmed: false },
  { id: "M20", distance: 999, isConfirmed: false },
  { id: "M21", distance: 999, isConfirmed: false },
  { id: "M22", distance: 999, isConfirmed: false },
  { id: "M23", distance: 999, isConfirmed: false },
  { id: "M24", distance: 999, isConfirmed: false },
  { id: "M25", distance: 999, isConfirmed: false },
  { id: "M26", distance: 999, isConfirmed: false },
  { id: "M27", distance: 999, isConfirmed: false },
  { id: "M28", distance: 999, isConfirmed: false },

  // 名港線
  { id: "E01", distance: 999, isConfirmed: false },
  { id: "E02", distance: 999, isConfirmed: false },
  { id: "E03", distance: 999, isConfirmed: false },
  { id: "E04", distance: 999, isConfirmed: false },
  { id: "E05", distance: 999, isConfirmed: false },
  { id: "E06", distance: 999, isConfirmed: false },
  { id: "E07", distance: 999, isConfirmed: false },

  // 鶴舞線
  { id: "T01", distance: 999, isConfirmed: false },
  { id: "T02", distance: 999, isConfirmed: false },
  { id: "T03", distance: 999, isConfirmed: false },
  { id: "T04", distance: 999, isConfirmed: false },
  { id: "T05", distance: 999, isConfirmed: false },
  { id: "T06", distance: 999, isConfirmed: false },
  { id: "T07", distance: 999, isConfirmed: false },
  { id: "T08", distance: 999, isConfirmed: false },
  { id: "T09", distance: 999, isConfirmed: false },
  { id: "T10", distance: 999, isConfirmed: false },
  { id: "T11", distance: 999, isConfirmed: false },
  { id: "T12", distance: 999, isConfirmed: false },
  { id: "T13", distance: 999, isConfirmed: false },
  { id: "T14", distance: 999, isConfirmed: false },
  { id: "T15", distance: 999, isConfirmed: false },
  { id: "T16", distance: 999, isConfirmed: false },
  { id: "T17", distance: 999, isConfirmed: false },
  { id: "T18", distance: 999, isConfirmed: false },
  { id: "T19", distance: 999, isConfirmed: false },
  { id: "T20", distance: 999, isConfirmed: false },

  // 桜通線
  { id: "S01", distance: 999, isConfirmed: false },
  { id: "S02", distance: 999, isConfirmed: false },
  { id: "S03", distance: 999, isConfirmed: false },
  { id: "S04", distance: 999, isConfirmed: false },
  { id: "S05", distance: 999, isConfirmed: false },
  { id: "S06", distance: 999, isConfirmed: false },
  { id: "S07", distance: 999, isConfirmed: false },
  { id: "S08", distance: 999, isConfirmed: false },
  { id: "S09", distance: 999, isConfirmed: false },
  { id: "S10", distance: 999, isConfirmed: false },
  { id: "S11", distance: 999, isConfirmed: false },
  { id: "S12", distance: 999, isConfirmed: false },
  { id: "S13", distance: 999, isConfirmed: false },
  { id: "S14", distance: 999, isConfirmed: false },
  { id: "S15", distance: 999, isConfirmed: false },
  { id: "S16", distance: 999, isConfirmed: false },
  { id: "S17", distance: 999, isConfirmed: false },
  { id: "S18", distance: 999, isConfirmed: false },
  { id: "S19", distance: 999, isConfirmed: false },
  { id: "S20", distance: 999, isConfirmed: false },
  { id: "S21", distance: 999, isConfirmed: false },

  // 上飯田線
  { id: "K01", distance: 999, isConfirmed: false },
  { id: "K02", distance: 999, isConfirmed: false },
];

export default distanceFromNodeList;